#!/usr/bin/env python3

import argparse
import os
import sys

from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import TerminalFormatter

def main():
	parser = argparse.ArgumentParser(description='')
	parser.add_argument("lang",
						type=str.lower,
						help='The snippet\'s language')
	parser.add_argument("snippet",
						type=str.lower,
						help='The code snippet you want to display')
	args = parser.parse_args()

	try:
		filename = os.path.join(os.path.dirname(__file__), 'snippets', args.lang, args.snippet+'.txt')
		with open(filename, 'r') as f:
			lexer = get_lexer_by_name(args.lang, stripall=True)
			formatter = TerminalFormatter(bg='dark')
			sys.stdout.write(highlight(f.read(), lexer, formatter))
	except Exception as e:
		print(e)

if __name__ == "__main__":
	main()
